language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT IDEA_VERSION=14.1.6
    - TARGET=IT IDEA_VERSION=15.0.3
    - TARGET=IT IDEA_VERSION=2016.1.2

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
    - '$HOME/.sonar'

notifications:
  email: false

notifications:
  email: false
  webhooks:
    urls:
    # URL to QA hook, including credentials
      - secure: "de1c8cBBGrR4qtjZVrf8m+aA3ADULZiEoXq9AMhLgsjRmYbix4YE9UagliNCPKwqKGjcyRVT+2tSZvlMlgFB/JJSZxUdvHEeoTV5QjKE/vbthhic/0ZIjuo32B0X9fATddKPgbDfpuozewLUzEB2FZaHCwJz/8y/kMr1xUhkD9Q="
    on_start: always
