language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT IDEA_VERSION=14.1.6
    - TARGET=IT IDEA_VERSION=15.0.3
    - TARGET=IT IDEA_VERSION=2016.1.2

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
    - '$HOME/.sonar'

notifications:
  email: false
