language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  matrix:
    - JOB=CI IJ_VERSION=14.1
    - JOB=CI IJ_VERSION=15.0.1 
    - PR_ANALYSIS=true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
